import { Node, Edge, Position, MarkerType } from "reactflow";

export const initialNodes: Node[] = [
  {
    id: "1",
    type: "input",
    data: { label: "JUNUS" },
    position: { x: 0, y: -10 },
    type: "customNode",
    sourcePosition: Position.Bottom,
  },
  {
    id: "2",
    data: { label: "Products" },
    position: { x: -500, y: 100 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "3",
    data: { label: "User Experience" },
    position: { x: 480, y: 100 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "4",
    data: { label: "Tokenized Real Estate" },
    position: { x: -500, y: 185 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "5",
    data: { label: "Lending & Borrowing" },
    position: { x: -10, y: 185 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "6",
    data: { label: "ETFs" },
    position: { x: 190, y: 185 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "7",
    data: { label: "Private Credit" },
    position: { x: 350, y: 185 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "8",
    data: { label: "Assets" },
    position: { x: -500, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "9",
    data: { label: "Strategies" },
    position: { x: -200, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "10",
    data: { label: "Increased Capital Efficiency" },
    position: { x: -60, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "11",
    data: { label: "Boosted Yields (Leverage)" },
    position: { x: 40, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "12",
    data: { label: "U.S. Treasury Bonds" },
    position: { x: 140, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "13",
    data: { label: "Macrotrends (AI, Cloud Robotics...)" },
    position: { x: 240, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "14",
    data: { label: "Cross-Border Payment Companies" },
    position: { x: 350, y: 280 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "15",
    data: { label: "Exotic Properties" },
    position: { x: -500, y: 370 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "16",
    data: { label: "High appreacition Properties" },
    position: { x: -400, y: 370 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "17",
    data: { label: "Renting" },
    position: { x: -300, y: 370 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "18",
    data: { label: "Modular Homes" },
    position: { x: -200, y: 370 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "19",
    data: { label: "Off-plan" },
    position: { x: -100, y: 370 },
    type: "customNode",
    targetPosition: Position.Top,
  },
  {
    id: "20",
    data: { label: "Wide Range of Yield Opportunities" },
    position: { x: 460, y: 180 },
    type: "customNodeRight",
    targetPosition: Position.Right,
  },
  {
    id: "21",
    data: { label: "Secure and Regulatory Compliant" },
    position: { x: 460, y: 230 },
    type: "customNodeRight",
    targetPosition: Position.Right,
  },
  {
    id: "22",
    data: { label: "User-friendly for Web2 and Web3 Users" },
    position: { x: 460, y: 280 },
    type: "customNodeRight",
    targetPosition: Position.Right,
  },
  {
    id: "23",
    data: { label: "100% Revenue Sharing" },
    position: { x: 460, y: 330 },
    type: "customNodeRight",
    targetPosition: Position.Right,
  },
  {
    id: "24",
    data: { label: "Portfolio Dashboard" },
    position: { x: 460, y: 380 },
    type: "customNodeRight",
    targetPosition: Position.Right,
  },
];

export const initialEdges: Edge[] = [
  {
    id: "edge-button1",
    source: "1",
    target: "2",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button2",
    source: "1",
    target: "3",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button3",
    source: "2",
    target: "4",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button4",
    source: "2",
    target: "5",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button5",
    source: "2",
    target: "6",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button6",
    source: "2",
    target: "7",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button7",
    source: "4",
    target: "8",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button8",
    source: "4",
    target: "9",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button9",
    source: "5",
    target: "10",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button10",
    source: "5",
    target: "11",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button11",
    source: "6",
    target: "12",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button12",
    source: "6",
    target: "13",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button13",
    source: "7",
    target: "14",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button14",
    source: "8",
    target: "15",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button15",
    source: "8",
    target: "16",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button16",
    source: "9",
    target: "17",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button17",
    source: "9",
    target: "18",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button18",
    source: "9",
    target: "19",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "bottom",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button19",
    source: "3",
    target: "20",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button20",
    source: "3",
    target: "21",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button21",
    source: "3",
    target: "22",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button22",
    source: "3",
    target: "23",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
  {
    id: "edge-button23",
    source: "3",
    target: "24",
    type: "buttonedge",
    sourceHandle: "top",
    targetHandle: "right",
    markerEnd: {
      type: MarkerType.Arrow,
      color: "black",
      width: 18,
      height: 18,
      strokeWidth: 1.1,
    },
  },
];
